name: 'Entro Security PR Scanner'
description: 'Scan PRs using Entro security scan API'
inputs:
  api-endpoint:
    description: 'Entro API endpoint'
    required: true
    default: 'https://api.entro.security'
  api-token:
    description: 'Entro API token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Run scanner
      shell: bash
      env:
        ENTRO_API_ENDPOINT: ${{ inputs.api-endpoint }}
        ENTRO_TOKEN: ${{ inputs.api-token }}
      run: |
        cd ${{ github.action_path }}
        go run . ${{ github.workspace }}
